### ISSUE TITLE
0.9.1 broken

### ISSUE THREAD

**Issue by martyalicante** [NodeBB-Community/nodebb-plugin-shortcuts#5]
it makes nodes to crash upon entering on plugin list

27/11 21:48 [28151] - error: TypeError: Invalid Version: 1.0.2+@{build}
    at new SemVer (/home/9node/NodeBB/node_modules/semver/semver.js:293:11)
    at SemVer.compare (/home/9node/NodeBB/node_modules/semver/semver.js:342:13)
    at compare (/home/9node/NodeBB/node_modules/semver/semver.js:566:31)
    at Function.gt (/home/9node/NodeBB/node_modules/semver/semver.js:595:10)
    at async.each.pluginArray (/home/9node/NodeBB/src/plugins.js:269:44)
    at /home/9node/NodeBB/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/home/9node/NodeBB/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/home/9node/NodeBB/node_modules/async/lib/async.js:209:22)
    at /home/9node/NodeBB/src/plugins.js:243:10
    at /home/9node/NodeBB/node_modules/async/lib/async.js:52:16
    at /home/9node/NodeBB/node_modules/async/lib/async.js:1204:30
TypeError: Invalid Version: 1.0.2+@{build}
    at new SemVer (/home/9node/NodeBB/node_modules/semver/semver.js:293:11)
    at SemVer.compare (/home/9node/NodeBB/node_modules/semver/semver.js:342:13)
    at compare (/home/9node/NodeBB/node_modules/semver/semver.js:566:31)
    at Function.gt (/home/9node/NodeBB/node_modules/semver/semver.js:595:10)
    at async.each.pluginArray (/home/9node/NodeBB/src/plugins.js:269:44)
    at /home/9node/NodeBB/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/home/9node/NodeBB/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/home/9node/NodeBB/node_modules/async/lib/async.js:209:22)
    at /home/9node/NodeBB/src/plugins.js:243:10
    at /home/9node/NodeBB/node_modules/async/lib/async.js:52:16
    at /home/9node/NodeBB/node_modules/async/lib/async.js:1204:30

**Comment by frissdiegurke** [comment]
It's needed to install via npm. The git repository only contains the "source code" which gets some custom compilation into final product.
Use the [NodeBB Grunt](https://github.com/NodeBB-Community/nodebb-grunt) Framework for deployment and development.

**Comment by martyalicante** [comment]
Ok thank tou
Can you add nbbpm compatibility then so it appears on admin plugin zone?

About grunt. No sure what you mean. I dont know how to use that without a description o a how to guide

**Comment by frissdiegurke** [comment]
There is nbbpm compatibility stated (see [this](https://packages.nodebb.org/api/v1/suggest?package=nodebb-plugin-shortcuts&version=0.9.1) for direct NBBPM API check).
It's compatible with `~0.9.0`.

The grunt setup has a basic *Workflow* wiki page. It's not documented how to adopt an existing module thought. Improving this step (documentation and code-wise) is still on my TODO list ;-)
